"""Adding username to users table

Revision ID: 4eac8019c0e4
Revises: ad93a7cc0d82
Create Date: 2025-01-13 03:04:20.397093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eac8019c0e4'
down_revision: Union[str, None] = 'ad93a7cc0d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('username', sa.String(), nullable=False))
    op.alter_column('auth_users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_auth_users_email', table_name='auth_users')
    op.create_index(op.f('ix_common_auth_auth_users_email'), 'auth_users', ['email'], unique=True, schema='common_auth')
    op.create_unique_constraint(None, 'auth_users', ['username'], schema='common_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_users', schema='common_auth', type_='unique')
    op.drop_index(op.f('ix_common_auth_auth_users_email'), table_name='auth_users', schema='common_auth')
    op.create_index('ix_auth_users_email', 'auth_users', ['email'], unique=True)
    op.alter_column('auth_users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('auth_users', 'username')
    # ### end Alembic commands ###
