"""Adding missing users columns

Revision ID: 9b063c446914
Revises: 4eac8019c0e4
Create Date: 2025-05-27 19:18:28.234560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b063c446914'
down_revision: Union[str, None] = '4eac8019c0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('auth_users', sa.Column('details', sa.JSON(), nullable=True))
    op.drop_index('ix_common_auth_auth_users_email', table_name='auth_users')
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.create_index('ix_common_auth_auth_users_email', 'auth_users', ['email'], unique=True)
    op.drop_column('auth_users', 'details')
    op.drop_column('auth_users', 'name')
    # ### end Alembic commands ###
